### ISSUE TITLE
Unicode handling

### ISSUE THREAD

**Issue by sr-murthy** [OasisLMF/OasisUI#10]
A number of methods in the server utils module

https://github.com/OasisLMF/OasisUI/blob/develop/src/flamingo_api_server/flamingo_utils.py

are not Unicode friendly in the file IO - currently all the file IO code in this module uses the built-in `open` method, which doesn't allow you to specify an encoding, rather than the `io.open` method which does. This is a potential problem if Unicode data is being read from or written to file, and affects the following steps

* load programme data (https://github.com/OasisLMF/OasisUI/blob/develop/src/flamingo_api_server/flamingo_utils.py#L111)
* generate Oasis files (https://github.com/OasisLMF/OasisUI/blob/develop/src/flamingo_api_server/flamingo_utils.py#L622)
* process keys (https://github.com/OasisLMF/OasisUI/blob/develop/src/flamingo_api_server/flamingo_utils.py#L520)
* generate summary files (https://github.com/OasisLMF/OasisUI/blob/develop/src/flamingo_api_server/flamingo_utils.py#L321), which affects the model run step

The solution is to replace all occurences of the built-in `open` method with the `io.open` method and the `encoding="utf-8"` argument, e.g.

        ...
        with open(schema_filepath, "w") as schema_file:
        ...

should be replaced by

        ...
        with io.open(schema_filepath, 'w', encoding='utf-8') as schema_file:
        ...

**Comment by sr-murthy** [comment]
@sambles @mpinkerton-oasis @benhayes21

**Comment by sambles** [comment]
Commit: 921d333 

Switched the non-binary file opens but left binary in place due to not needed an encoding type

**Comment by sr-murthy** [comment]
@sambles Note my comment here. 

https://github.com/OasisLMF/OasisUI/commit/921d33370e4e130fd6da8a0704c3338843271463#commitcomment-31594302

I think `open` should be replaced with `io.open` everywhere in the utils module - those other files which are being opened using `open` are actually all CSV files, not binary files. So I don't know why the file mode is `wb` - newlines in Windows files are treated differently depending on whether the file is binary or text, but the files being written are all text not binary files.

Separately, using `with io.open(...` would allow you to reduce the file IO code by removing the `<file>.close()` statements, e.g. on line 360 we have

    destination = open(gulsummaryxref, 'wb')
    destination.write("coverage_id,summary_id,summaryset_id\n")
    shutil.copyfileobj(
        open(input_location + "/gulsummaryxref_temp.csv", 'rb'),
        destination)
    destination.close()

This can be simplified to

    with io.open(gulsummaryxref, 'w', encoding='utf-8') as destination:
        destination.write("coverage_id,summary_id,summaryset_id\n")
        ...

If you do this everywhere the file IO code will be smaller.

It would be better for this UI code to use MDK to generate and write Oasis files, but that would be a another project.

**Comment by sr-murthy** [comment]
I will make these changes at some point next week.

**Comment by mpinkerton-oasis** [comment]
That sounds like a reasonable easy fix. Could we try and get this done on Monday, so we can include it in the new build?

**Comment by sr-murthy** [comment]
The error that JBA reported yesterday, which was triggered in the source -> canonical transformation step in the MDK, was actually due to the source file not being saved properly by the user. It was "fixed" by saving the file using UTF8 encoding.

I am working on completing the FM acceptance tests, so if this is required by Monday perhaps @sambles can implement the changes I described above - replacing `open` with `io.open` everywhere in the utils module, and also using the `with` construct (which would make it possible to remove all the file handle close statements). One thing I don't understand why the existing file IO code in this module uses `wb` as the file mode for writing the GUL + FM input files, which are all CSV files.

**Comment by sr-murthy** [comment]
The error that JBA reported yesterday, which was triggered in the source -> canonical transformation step, was actually due to the source file not being saved properly by the user. It was "fixed" by saving the file using UTF8 encoding.

I am working on completing the FM acceptance tests, so if this is required by Monday perhaps @sambles can implement the changes I described above - replacing `open` with `io.open` everywhere in the utils module, and also using the `with` construct (which would make it possible to remove all the file handle close statements). One thing I don't understand why the existing file IO code in this module uses `wb` as the file mode for writing the GUL + FM input files, which are all CSV files.

**Comment by sambles** [comment]
shouldn't be an issue after (1.0.0) moving to the new API  where the transforms are no longer in Flamingo
