### ISSUE TITLE
UI Output configuration redesign

### ISSUE THREAD

**Issue by fvitalini** [OasisLMF/OasisUI#148]
UI Output Configuration to be re-designed to integrate OED fields. The summary levels and the Reports should be dynamically fetched using #147 and the UI should be modified according to mock-up attached.

Substitute tag "Portfolio" with "Summary" to avoid confusion.

[Oasis  (1).pdf](https://github.com/OasisLMF/OasisUI/files/3397331/Oasis.1.pdf)

**Comment by nfarabullini** [comment]
Selection of multiple oed fields functions as a composite aggregator and should be passed as a vector to the analysis settings
