### ISSUE TITLE
Logs not accessible from UI

### ISSUE THREAD

**Issue by rtahiry** [OasisLMF/OasisUI#157]
Logs are not currently accessible from the UI. This worked in the previous versions.
![oasis_log_missing_from_ui](https://user-images.githubusercontent.com/28949992/62695449-b8ddc080-ba19-11e9-8bb2-ac82c7af3116.png)

**Comment by mpinkerton-oasis** [comment]
@rtahiry this functionality hasn't changed. What logs were you able to access previously?

**Comment by rtahiry** [comment]
@mpinkerton-oasis, I think we used to be able to download or at least view the worker.log from the UI when things go wrong. In the screenshot above, the analysis failed but no log is shown on the UI.
