### ISSUE TITLE
Wrong name used when downloading files

### ISSUE THREAD

**Issue by carlfischerjba** [OasisLMF/OasisUI#16]
Instead of using WinSCP to copy the output files back to my workstation, I've been selecting a file under Output Files > File List, then moving to the File Contents tab, then clicking the Export to Excel button. The downloaded data is correct but the file is always named the same even if I select a different one. 
If I refresh the Flamingo page and log in again, it's correct for the first file I download but then that name gets reused for all subsequent ones.

![image](https://user-images.githubusercontent.com/15981535/52052195-b6bc1600-254d-11e9-8838-4868b056de6a.png)

**Comment by carlfischerjba** [comment]
We appear to be using version 0.397.2 of the Flamingo images.

**Comment by fvitalini** [comment]
This issue refers to an older, obsolete version of the app.
