### ISSUE TITLE
UI freezes when refresh button for details of analysis is clicked

### ISSUE THREAD

**Issue by rtahiry** [OasisLMF/OasisUI#182]
UI freezes when refresh button for details of analysis is clicked
![Capture](https://user-images.githubusercontent.com/28949992/67053530-6fce8900-f18d-11e9-8d6b-f29aab98077b.PNG)
![Capture2](https://user-images.githubusercontent.com/28949992/67053533-7230e300-f18d-11e9-8a4f-462469c3889d.PNG)

**Comment by nfarabullini** [comment]
This issue was fixed in branch feature/168-animate-refresh in relation to issue #168 . A pull request (#181) has been opened and should be merged into develop by the end of the day.
