### ISSUE TITLE
match the footer version number to the docker build tag

### ISSUE THREAD

**Issue by fvitalini** [OasisLMF/OasisUI#211]
Currently the footer is defined here:
https://github.com/OasisLMF/OasisUI/blob/develop/BFE_RShiny/oasisui/inst/app/ui_auth.R#L93 

Preferred option would be a dynamic update of the footer. Otherwise it could be sourced from a file, which can be incremented as per of the build process.

**Comment by nfarabullini** [comment]
edits made as part of branch for issue #210
