### ISSUE TITLE
When advanced is not open in the "Output Configuration" then boolean model settings are set to '{}' instead of the default value

### ISSUE THREAD

**Issue by rtahiry** [OasisLMF/OasisUI#225]
When advanced is not open in the "Output Configuration" then boolean model settings are set to '{}' instead of the default value.

E.g., here is a screen capture where I clicked directly on Execute Run after completing the custom output settings.

![Capture](https://user-images.githubusercontent.com/28949992/81530448-3ddc7880-93a4-11ea-9d8e-da981d01967e.PNG)

**Comment by rtahiry** [comment]
Forgot to say that this is for complex model integrations.

**Comment by RolandASc** [comment]
From a quick look at the code it doesn't seem that this should be happening normally.
Could you maybe provide your model_settings or a relevant excerpt thereof?
Are only boolean parameters affected by this?
