### ISSUE TITLE
Alignment of submit button for create portfolio

### ISSUE THREAD

**Issue by bbetov** [OasisLMF/OasisUI#228]
Minor issue: On the "Choose Portfolio" page, when you click "Create Portfolio", a new box appears on the bottom where you type the name of the portfolio.

The "Submit" button should probably be right - aligned.

<img width="1315" alt="Screenshot_1" src="https://user-images.githubusercontent.com/23485043/83666587-01a2cf00-a582-11ea-94b8-651c8d21ba07.png">

**Comment by nfarabullini** [comment]
closed with PR #263
