### ISSUE TITLE
Update R version to 3.5.2 and manage packages dependencies

### ISSUE THREAD

**Issue by fvitalini** [OasisLMF/OasisUI#24]
The latest R version is 3.5.2. 
The app specifications should be updated to use the latest version of R

Moreover, minimal version specifications should be provided in the `DESCRIPTION` file.

**Comment by RolandASc** [comment]
The final choices are to use the second-latest version of R and specify exact package versions in the `DESCRIPTION` file. Thus things remain stable and in sync with `MRAN` and `rocker/r-ver`.
