### ISSUE TITLE
UI is getting freezes after one minute of inactivity

### ISSUE THREAD

**Issue by kprasadpn** [OasisLMF/OasisUI#264]
Hi ,
Currently we are  using 1.10 version of UI , and after login to the UI  the screen its getting freezed after one minute inactivity  .
Is  there any configuration that we need to change to increase the time period  . 
Currently we are using the default configuration while deploying the UI image .

**Comment by benhayes21** [comment]
hi @kprasadpn 

We're unable to recreate this issue - can you provide more information regarding how you have deployed the UI please and the browser that you're using?

**Comment by kprasadpn** [comment]
We are using Microsoft Edge browser and application is deployed in AKS .

**Comment by sambles** [comment]
Issue cause by Cluster ingress settings, fixed with https://github.com/OasisLMF/OasisPlatform/pull/659
