### ISSUE TITLE
Export to Zip issue 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisUI#279]
## Issue Description
The `Export to Zip` button seems to fail when multiple files have been selected. 
![Screenshot from 2022-03-16 11-29-34](https://user-images.githubusercontent.com/9889973/158580530-9fb9422f-ceb7-4f17-a40c-d4287a57a782.png)

## Version / Environment information
UI: `1.11.3`
Oasis: `1.24.0`

## Example data / logs
Error warnings from UI application

```
Warning: Error in fwrite: Column 4's length (0) is not the same as column 1's length (1)
  [No stack trace available]
Read 64 items
```

```
Warning: Error in fwrite: Row 1 of list column is type 'list' - not yet implemented. fwrite() can write list columns containing items which are atomic vectors of type logical, integer, integer64, double, complex and character.
  [No stack trace available]
```

**Comment by RolandASc** [comment]
@sambles I wonder whether it's just an issue when mixing `json` files in, or more generally?

**Comment by sambles** [comment]
oh I see what you mean: 

Selecting multiple `csv` type files works, the problem happens when selecting `json` and `txt` which cause the download to fail.
