### ISSUE TITLE
Incorrect validation summary graph

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisUI#280]
## Issue Description
The summary validation graph is not matching the table, the only bar shown is the `noreturn` TIV amount.   

![Screenshot 2022-03-16 at 11 45 45](https://user-images.githubusercontent.com/9889973/158586602-be264e46-a8a0-4a22-8307-6613f714ad5d.png)

## Version / Environment information
UI: `1.11.3`
Oasis: `1.24.0`

**Comment by MattDonovan82** [comment]
I would even consider removing this graph altogether. I'm not sure it brings anything to the user experience?

**Comment by sambles** [comment]
It might be helpful as a quick visual breakdown to see roughly where the portfolio breaks down between `success` / `nomatch` / `fail` 

As it is the x axis doesn't makes much sense, at least to me, I don't think it needs `number of locations` or `tiv`
`

**Comment by benhayes21** [comment]
looks like the table is duplicating the json data
not sure that a graphical representation is required - unless you can think of a good way of representing it

**Comment by benhayes21** [comment]
https://github.com/OasisLMF/OasisPiWind/blob/master/tests/inputs/SourceLocOEDPiWind.csv

**Comment by RolandASc** [comment]
the original issue here is that the graph wasn't adapted when more detailed return statuses were introduced. I am now fixing that first, then we can maybe re-consider

in general I do think that the percentages in the graph are useful to see that 80% of the locations were successful while that corresponds to only 65% of TIV being successful (for example)

**Comment by benhayes21** [comment]
Ben to test
