### ISSUE TITLE
Error when trying to view IG Logs

### ISSUE THREAD

**Issue by nicksamps** [OasisLMF/OasisUI#281]
## Issue Description
Nothing happens when I click "View IG Logs" after input generation.

## Steps to Reproduce (Bugs only)
1. Create an analysis and run input generation
2. Click "Show IG Log"

## Version / Environment information
UI Version 1.1.3
coreoasis/api_server:1.23.8 

## Example data / logs
```
oasis-ui_1        | No encoding supplied: defaulting to UTF-8.
oasis-ui_1        | Warning: Error in FUN: argument is not a character vector
oasis-ui_1        |   2: runApp
oasis-ui_1        |   1: oasisui::runOasisui
```

**Comment by benhayes21** [comment]
sam to recreate
