### ISSUE TITLE
UI crash at output dashboard with zipped exposure files 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisUI#286]
## Issue Description
Output Dashboard gray screen crashes when loading results from run using zipped exposure run (PiWind)  

## Version / Environment information
Oasislmf: `1.26.0`
Platform branch: `platoform-2.0-develop` (Azure)
OasisUI: `1.11.3`

## Example data / logs
```
input$dt_analyses_rows_selected is changed to: 1
analysisId changed to 6
selected analysis ID is 6
updating result$dashboardanaID because submodulesList$step3_configureOutput$dashboardAnaID() changed to: 6
Navigate to Single browse
replacing icons
Updating preselected row because anaID() changed to 6
updating ana outputs data list
Warning in FUN(X[[i]], ...) : NAs introduced by coercion
Warning: Error in : Invalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.
  2: runApp
  1: oasisui::runOasisui
delete  
```
[piwind_loc_oed.zip](https://github.com/OasisLMF/OasisUI/files/8991065/piwind_loc_oed.zip)
[piwind_acc_oed.zip](https://github.com/OasisLMF/OasisUI/files/8991067/piwind_acc_oed.zip)

**Comment by RolandASc** [comment]
the crash happens because we read some data from the location file in order to produce the summary tab, and we haven't added any generic functionality to handle zipped exposure files

**Comment by RolandASc** [comment]
it was simple enough to add some code to handle zipped exposure files in the main function retrieving that data, so I have implemented that and this issue is resolved now

it doesn't mean that we will have full feature support for zipped files across the board though, so maybe we'll want to do something more later

**Comment by MattDonovan82** [comment]
@mtazzari would the functionality you mentioned last week regarding splitting the tar files help here?

The UI is generally slow when trying to export or even view the output files, especially if they are quite large.
