### ISSUE TITLE
Portfolio link section is hidden after each file upload

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisUI#287]
## Issue Description

After a file is uploaded and linked the file picker section is hidden, a user needs to reopened this for each file.  
![Screenshot from 2022-06-29 15-08-44](https://user-images.githubusercontent.com/9889973/176458656-2b26348d-ec31-4edb-8b31-da1fc23c52db.png)

## Version / Environment information
OasisUI 1.11.3

**Comment by RolandASc** [comment]
we agreed to leave it open by default, rather than closing it as soon as the analysis status is ready (which is basically always the case once a location file is provided)
