### ISSUE TITLE
Update rocker image 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisUI#288]
## Action points 
- [x] Add image CVE scanner (Trivy?) 
- [x] Update openssl / or removal 
- [ ] Look at updating shiny proxy 

## Issue Description
 The app's docker file is built from `rocker/r-ver:4.0.5`, this is based on **ubuntu:20:04**. 
 Which scanned for security issues the following CVE's are highlighted 
 
 
![app_CVE_overview](https://user-images.githubusercontent.com/9889973/178703227-c831fb52-0a9a-4f4d-a085-a6ed47e1a6fb.png)
![app_CVE](https://user-images.githubusercontent.com/9889973/178703239-a9130bcc-1cd8-4648-b470-8cc8f57197fc.png)

Ideally the app should be updated to run on   **ubuntu:22:04** (if possible)

**Comment by RolandASc** [comment]
According to https://github.com/rocker-org/rocker-versioned2#readme, they might start using Ubuntu 22.04 fairly soon, i.e. 90 days after the release (which was April 21).

Meanwhile we could either try to use their image and scripts and adapt them ourselves accordingly, or if it's just about the high severity vulnerability of openssl, probably just upgrade / clean that up for now.
