### ISSUE TITLE
User-interface crashes - if IL output is selected but there are no insured losses

### ISSUE THREAD

**Issue by dholdaway** [OasisLMF/OasisUI#294]
PROBLEM:
User-interface crashes when clicking "Proceed to Dashboard" (under "Configure Output & Run"), if IL output is selected but there are no insured losses. 

![Screenshot 2022-09-01 at 17 03 14](https://user-images.githubusercontent.com/2313317/187960764-013ba14c-1a3c-403e-85db-ff74b23ad3c3.png)

TO REPRODUCE:
- Set deductible very high in the acc file (higher than the TIV) 
- Configure Output to show insured losses
- Click "Proceed to Dashboard"
- UI will crash (screen greys out as if timing out)

 

EXPECTED BEHAVIOUR:
Would expect the output dashboard to be displayed and simply show zero insured losses

**Comment by benhayes21** [comment]
Ben to recreate

**Comment by benhayes21** [comment]
fixed with latest release
