### ISSUE TITLE
Combining summary and type output files in the UI

### ISSUE THREAD

**Issue by MattDonovan82** [OasisLMF/OasisUI#297]
Is it possible to output the 'summary' and 'type' files so they appear together in the same file?

For example, when looking at 'state' level outputs for the US, it would be useful to know what State each Summary ID represents without having to do a lookup in excel to match them. This is particularly important for those using the outputs directly from the UI. 

I'm not sure if this is more a platform issue rather than a UI issue?

**Comment by benhayes21** [comment]
This will tie in with Lot 3 requirements

**Comment by benhayes21** [comment]
I don't think this is a UI issue - but one that we should look into with file management behind the API/in Lot 3.

closing here
