### ISSUE TITLE
Modelling sub-perils in OasisUI

### ISSUE THREAD

**Issue by Raph692** [OasisLMF/OasisUI#318]
## Issue Description
We're not able to model sub-perils in the OasisUI. When running one of our earthquake models locally (which has separate vulnerability functions for 1. shaking only, 2. shaking + liquefaction, and 3. shaking + liquefaction + landslide), we're able to generate modelled losses for all sub-perils as long as we use all peril codes ("QEQ;QLF;QLS") in the column "LocPerilsCovered" of the location file. However, when trying to run the same location file in the OasisUI, we only get modelled losses for the first peril code (shaking only). Is there a setting to enable sub-peril modelling in the Oasis UI?

## Steps to Reproduce

1. Run the same location file with three different peril code combinations locally (peril code "QEQ" produces modelled AAL = X; peril code "QEQ;QLF" produces modelled AAL = Y; peril code "QEQ;QLF;QLS" produces modelled AAL = Z).
2. Run the same location file with peril code "QEQ;QLF;QLS" in the Oasis UI, which will produce modelled AAL = X (i.e., identical AAL as local run with "QEQ").

## Version / Environment information
MDK 1.28.2
windows 10/11 - WLS 2 - ubuntu 20.04

**Comment by benhayes21** [comment]
closing - parquet ap dict just needed updating to include all perils covered
