### ISSUE TITLE
Rename table buttons in step 2

### ISSUE THREAD

**Issue by fvitalini** [OasisLMF/OasisUI#50]
Rename table buttons in step 2 according to the mock-up
![image](https://user-images.githubusercontent.com/13469315/54262940-cfb5df00-456f-11e9-974b-a3b45be4453a.png)

- [x]  Button  "Start Input generation" already renamed "Generate inputs",  should be available (visible and active) if status text is Ready, run_completed, run_failed, run_in_progress and input_generation_failed. The button label should be show  "Cancel input generation" if status text is "input_generation_started". Based on the labels the button should perform different actions, respectively start and cancel the input generation via the appropriate API call. The button should be inactive if no row is selected.

- [x] Button Logs should fetch the traceback file equivalently to the current "Show logs" button.The button should be active if an analysis is selected in the table and inactive otherwise.

- [x] Button "Details" content to be developed in issue #51 . The button should be active if an analysis is selected in the table and inactive otherwise.

**Comment by nfarabullini** [comment]
Analyses table title needs to be the same in step 2 and 3

**Comment by nfarabullini** [comment]
Buttons "Logs" and "Details" need to be changed to "Show Log" and "Show Details" to keep consistency with the others' format
