### ISSUE TITLE
Update column header names

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisUI#54]
Update the column headers to be more user friendly:
- Translate internal column names to proper text and capitalize
- Use full descriptive information rather than IDs for fields such as model and portfolio.

Some annotations in the attached document.

**Comment by mpinkerton-oasis** [comment]
[
[Tables.docx](https://github.com/OasisLMF/OasisUI/files/2970981/Tables.docx)
](url)

**Comment by fvitalini** [comment]
As agreed, the columns "status" and "status_detailed" in the analyses table will remain separate. 
The model id and the portfolio id will not be visible for the basic user, but visible to an admin user, according to #61.

**Comment by fvitalini** [comment]
As discussed, replace>

-  Supplier id : supplier;
-  Id → ID
