### ISSUE TITLE
If run fails, inputs need to be regenerated

### ISSUE THREAD

**Issue by DanielFEvans** [OasisLMF/OasisUI#60]
If my inputs generated successfully, but my run failed, I can not press "Proceed to Configure Output & Run" on the Choose Analysis page without re-generating my inputs. I would have thought that the inputs would be stored, and I could skip straight to retrying/reconfiguring my run.

**Comment by fvitalini** [comment]
Yes @DanielFEvans, that is because the app does not distinguish between the statuses "run failed" and "input generation failed". 
This will not be an issue with the next releases, since the development of #21 .
