### ISSUE TITLE
Admin mode

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisUI#61]
For admin/debug use, it is handy to see the IDs of analyses, portfolios etc. More generally, this data should be hidden from users. A flag will be added on the server side that will launch the application in admin/debug mode.

**Comment by fvitalini** [comment]
Related to issue #54

**Comment by fvitalini** [comment]
Added environment variable ADMON_MODE. The variable is used to decide whether to show portfolio id and model id in analyses table.
