### ISSUE TITLE
"Policy" Level Outputs not correct

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/OasisUI#9]
When running policy level outputs through flamingo, the fmsummaryxrex table assigns summaryid based on agg_id but it needs to be based on agg_id and layer_id.

Fix to take place in flamingo db to set summaryid properly (generateoasisfilesoutputs) and in flamingo_server_api to join back to this when appending business meaning to the output files

**Comment by RolandASc** [comment]
@benhayes21 I guess this is obsolete now and can be closed?

**Comment by benhayes21** [comment]
Yep...closing!
